"""
Page 5 — About This Data.

Explains the synthetic GTech dataset, how it is generated, and how this dashboard uses it.
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import streamlit as st

from components.ui import setup_page

setup_page(
    "About This Data",
    "Origins, purpose, and limitations of the metrics shown in this dashboard.",
)

st.markdown(
    """
**GTech** is a fictional B2B SaaS company modeled in this project. The product is an
operations platform for service businesses — invoicing, scheduling, payments, CRM, and
reporting — sold on **Starter**, **Pro**, and **Business** plans.

Everything you see here is **synthetic**. No real customers, revenue, or transactions
are represented.
"""
)

st.subheader("Why this data exists")

st.markdown(
    """
This dataset powers **AutoAnalyst**, an end-to-end analytics portfolio project. It
simulates a growing subscription business so the full stack can be demonstrated:

1. **Ingestion** — Python scripts generate daily operational records.
2. **Warehouse** — CSVs load into PostgreSQL `raw_*` tables.
3. **Modeling** — dbt builds staging views, core facts/dimensions, and reporting marts.
4. **Orchestration** — Airflow refreshes the pipeline on a daily schedule.
5. **Visualization** — this dashboard reads from dbt marts in the `analytics` schema.

The goal is to practice realistic SaaS analytics workflows — MRR, churn, engagement,
transaction health, and anomaly monitoring — without using proprietary or sensitive data.
"""
)

st.subheader("How it is generated")

col1, col2 = st.columns(2)

with col1:
    st.markdown(
        """
**Generator scripts** (repo: `src/ingestion/`)

- `generate_historical_backfill.py` — one-time history from **January 1, 2022** through today
- `generate_daily_batch.py` — incremental daily batches appended by Airflow or manual runs

**Libraries:** Python, pandas, NumPy, and [Faker](https://faker.readthedocs.io/) for
realistic names, companies, and emails. Row volumes, churn rates, and plan mix are
tuned with weighted random distributions — not copied from any real company.
"""
    )

with col2:
    st.markdown(
        """
**What gets simulated each day**

| Entity | Examples |
|--------|----------|
| Accounts | Industry, region, acquisition channel, company size |
| Users | Roles, login activity, onboarding status |
| Subscriptions | Plan tier, billing period, trials, cancellations |
| Product events | Feature usage, sessions, success/failure rates |
| Transactions | Payment amounts, status, refunds, failure reasons |

Subscriptions include realistic **~3–5% monthly churn**. Transaction volume ramps over
time to mimic SaaS growth. A static **feature catalog** (15 product features) drives
engagement metrics.
"""
    )

st.subheader("What this dashboard reads")

st.markdown(
    """
The dashboard does **not** query raw CSVs or `raw_*` tables directly. It reads dbt
reporting marts in PostgreSQL:

- `analytics.mart_daily_kpis` — wide daily executive snapshot (KPI cards, most charts)
- `analytics.mart_mrr` — MRR broken out by plan
- `analytics.mart_anomaly_candidates` — metrics flagged for investigation

Those marts are rebuilt whenever ingestion runs and `dbt run` completes. Use **Refresh data**
in the sidebar after a new pipeline run.
"""
)

st.subheader("Important limitations")

st.markdown(
    """
- **Not production data** — patterns are plausible but invented; do not use for business decisions.
- **Deterministic only where coded** — daily batches are idempotent for a given date, but
  historical backfill uses randomness; re-running backfill produces a different universe.
- **Anomalies are rule-based** — candidates come from dbt logic in `mart_anomaly_candidates`,
  not from a live monitoring system.
"""
)

st.divider()

st.caption(
    "AutoAnalyst · Synthetic GTech dataset · Generated by Gregory Joshua · "
    "[GitHub](https://github.com/0GregoryJ/AutoAnalyst) · "
    "[LinkedIn](https://www.linkedin.com/in/gregjoshua/)"
)
